;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; File: mfunc6.mac
; Desc: Tool Change Macro
;
; Stages:
;   ATCStage
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;Skip if graphing or searching
IF #4202 || #4201 THEN GOTO 1000
IF #50001       ; Prevent lookahead
M109 /1/2       ; Disable overrides

S0
M5              ; stop spindle
M9              ; Turn off coolant
M101 /50012     ; wait for ZeroSpeed_I (INP12) ON = spindle confirmed stopped before Z enters changer
G53 Z0          ; Move Z to tool change position
M107            ; Send tool number 
G4 P.1          ; wait .1 second
M94 /8          ; Set M6_SV to start tool change stage
G4 p1           ; wait 1 second (can I shorten this wait?)
M100 /93016     ; ATCStage RST
M95 /8          ; reset M6_SV to stop tool change stage when done

N1000           ; end of program