;  Header  
N0010 ; CNC code generated by Intercon from Centroid Corp. v. 5.21
; Program:      DEMO1.ICN
; Programmer:   JDA
; Date:   Thu Oct 17 07:11:25 1996
M25 G49    ; Goto Z home, cancel tool length offset 
G17 G40    ; Setup for XY plane, no cutter comp,
G20        ; inch measurements,
G80        ; cancel canned cycles,
G90        ; absolute positioning,
G98        ; canned cycle initial point return 
;  Tool change  
N0020 G49 H0 M25
G0 X-3 Y0
T1 S4200 M6
M3
G4 P3.00  ; pause for dwell
G43 D1
;  Circular pocket  
N0030  X1.2374 Y1.1759 Z0.1 H1
G1 G91 Z-0.1 F10
 Y0.123 Z-0.1
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G3 X-0.0625 Y-0.0615 J-0.0625 F30
 I0.0625
 X0.0625 I0.0312
G0 G90 Z0.1
;  Circular pocket  
N0040  X-1.2374 Y1.1759
G1 G91 Z-0.1 F10
 Y0.123 Z-0.1
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G3 X-0.0625 Y-0.0615 J-0.0625 F30
 I0.0625
 X0.0625 I0.0312
G0 G90 Z0.1
;  Circular pocket  
N0050  X-1.2374 Y-1.2989
G1 G91 Z-0.1 F10
 Y0.123 Z-0.1
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G3 X-0.0625 Y-0.0615 J-0.0625 F30
 I0.0625
 X0.0625 I0.0312
G0 G90 Z0.1
;  Circular pocket  
N0060  X1.2374 Y-1.2989
G1 G91 Z-0.1 F10
 Y0.123 Z-0.1
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G1 Y-0.123
 Y0.123 Z-0.1 F10
 Y-0.0615
G2 Y0.0615 J0.0308 F20
 J-0.0615
G3 X-0.0625 Y-0.0615 J-0.0625 F30
 I0.0625
 X0.0625 I0.0312
G0 G90 Z0.1
;  Tool change  
N0070 G49 H0 M25
G0 X-3 Y0
T2 S3000 F30 M6
M3
G4 P3.00  ; pause for dwell
G43 D2
;  Circular pocket  
N0080  X0 Y-0.365 Z0.1 H2
G1 G91 Z-0.1 F10
 Y0.73 Z-0.125
 Y-0.365
G2 Y0.1825 J0.0912
 X-0.1825 Y-0.1825 J-0.1825
 X0.1825 Y0.365 I0.4562
 J-0.365
G1 Y-0.73
 Y0.73 Z-0.125
 Y-0.365
G2 Y0.1825 J0.0912
 X-0.1825 Y-0.1825 J-0.1825
 X0.1825 Y0.365 I0.4562
 J-0.365
G1 Y-0.73
 Y0.73 Z-0.125
 Y-0.365
G2 Y0.1825 J0.0912
 X-0.1825 Y-0.1825 J-0.1825
 X0.1825 Y0.365 I0.4562
 J-0.365
G1 Y-0.73
 Y0.73 Z-0.125
 Y-0.365
G2 Y0.1825 J0.0912
 X-0.1825 Y-0.1825 J-0.1825
 X0.1825 Y0.365 I0.4562
 J-0.365
G3 X-0.375 Y-0.365 J-0.3751
 I0.375
 X0.375 I0.1875
G0 G90 Z0.1
;  Rapid traverse  
N0090  X-2 Y-1
;  Cutter comp  
N0100 G41  ; Left  
;  Linear mill  
N0110 G1 X-2 Y-1
;  Linear mill  
N0120  X-2 Y-1 Z-0.1
;  Linear mill  
N0130  X-2 Y1.75
G2 X-1.75 Y2 I0.25
;  Linear mill  
N0140 G1 X1.75 Y2
G2 X2 Y1.75 J-0.25
;  Linear mill  
N0150 G1 X2 Y-1.75
G2 X1.75 Y-2 I-0.25
;  Linear mill  
N0160 G1 X-1.75 Y-2
G2 X-2 Y-1.75 J0.25
;  Linear mill  
N0170 G1 X-2 Y-1
;  Cutter comp  
N0180 G40  ; Off   
;  Repeat to depth  
N0190  ; Begin code repetitions 
 ;  Move to start of contour  
G0 X-2 Y-1 Z0
;  Rapid traverse  
 X-2 Y-1
;  Cutter comp  
G41  ; Left  
;  Linear mill  
G1 X-2 Y-1
;  Linear mill  
 X-2 Y-1 Z-0.2
;  Linear mill  
 X-2 Y1.75
G2 X-1.75 Y2 I0.25
;  Linear mill  
G1 X1.75 Y2
G2 X2 Y1.75 J-0.25
;  Linear mill  
G1 X2 Y-1.75
G2 X1.75 Y-2 I-0.25
;  Linear mill  
G1 X-1.75 Y-2
G2 X-2 Y-1.75 J0.25
;  Linear mill  
G1 X-2 Y-1
;  Cutter comp  
G40  ; Off   
 ;  Move to start of contour  
G0 X-2 Y-1 Z-0.1
;  Rapid traverse  
 X-2 Y-1
;  Cutter comp  
G41  ; Left  
;  Linear mill  
G1 X-2 Y-1
;  Linear mill  
 X-2 Y-1 Z-0.3
;  Linear mill  
 X-2 Y1.75
G2 X-1.75 Y2 I0.25
;  Linear mill  
G1 X1.75 Y2
G2 X2 Y1.75 J-0.25
;  Linear mill  
G1 X2 Y-1.75
G2 X1.75 Y-2 I-0.25
;  Linear mill  
G1 X-1.75 Y-2
G2 X-2 Y-1.75 J0.25
;  Linear mill  
G1 X-2 Y-1
;  Cutter comp  
G40  ; Off   
 ;  Move to start of contour  
G0 X-2 Y-1 Z-0.2
;  Rapid traverse  
 X-2 Y-1
;  Cutter comp  
G41  ; Left  
;  Linear mill  
G1 X-2 Y-1
;  Linear mill  
 X-2 Y-1 Z-0.4
;  Linear mill  
 X-2 Y1.75
G2 X-1.75 Y2 I0.25
;  Linear mill  
G1 X1.75 Y2
G2 X2 Y1.75 J-0.25
;  Linear mill  
G1 X2 Y-1.75
G2 X1.75 Y-2 I-0.25
;  Linear mill  
G1 X-1.75 Y-2
G2 X-2 Y-1.75 J0.25
;  Linear mill  
G1 X-2 Y-1
;  Cutter comp  
G40  ; Off   
 ;  Move to start of contour  
G0 X-2 Y-1 Z-0.3
;  Rapid traverse  
 X-2 Y-1
;  Cutter comp  
G41  ; Left  
;  Linear mill  
G1 X-2 Y-1
;  Linear mill  
 X-2 Y-1 Z-0.5
;  Linear mill  
 X-2 Y1.75
G2 X-1.75 Y2 I0.25
;  Linear mill  
G1 X1.75 Y2
G2 X2 Y1.75 J-0.25
;  Linear mill  
G1 X2 Y-1.75
G2 X1.75 Y-2 I-0.25
;  Linear mill  
G1 X-1.75 Y-2
G2 X-2 Y-1.75 J0.25
;  Linear mill  
G1 X-2 Y-1
;  Cutter comp  
G40  ; Off   
;  Rapid traverse  
N0200 G0 X-2 Y-1 Z1
;  Rapid traverse  
N0210  X-3 Y0
;  End of program  
N0220 G49 H0 M25
G40        ; Cutter comp off
M5         ; Spindle Off
M9         ; Coolant Off
G80        ; Cancel canned cycles
 ; End of program
